### ISSUE TITLE
Only works in N. Virginia #1

### ISSUE THREAD

**Issue by JulieGoldberg** [censusreporter/census-postgres-scripts#13]
When I tried running the acs command in us-west-2 (Oregon), it told me:
An error occurred (InvalidAMIID.NotFound) when calling the RequestSpotInstances operation: The image id '[ami-a73264ce]' does not exist

When I guessed correctly that you were using us-east-1 (N. Virginia) and passed --region us-east-1 into the aws ec2 request-spot-images command, it was more successful. It said it created the machine pending review.

If there's a way to make the snapshot available in every AWS location, that would be great. If not, you should note that it's N. VA only and add the flag mentioned above.

**Comment by iandees** [comment]
Hi @JulieGoldberg! Thanks for pointing this out. The image mentioned in the readme is no longer available and I'll shortly be modifying the readme so it doesn't mention it. The preferred method of accessing the ACS data we generate is by loading the PostgreSQL dumps from here: http://censusreporter.tumblr.com/post/73727555158/easier-access-to-acs-data

**Comment by iandees** [comment]
Adjusted the readme in 86f0588b7f.
