### ISSUE TITLE
Character encoding problems in TIGER2017 data load

### ISSUE THREAD

**Issue by JoeGermuska** [censusreporter/census-postgres-scripts#20]
see, for example https://censusreporter.org/profiles/31000US15860-caaon-city-co-micro-area/

<img width="573" alt="image" src="https://user-images.githubusercontent.com/46313/45986193-a344ef80-c02f-11e8-8cea-c8bad8ac4d00.png">

**Comment by iandees** [comment]
I'm reimporting the TIGER data now to fix this.

**Comment by JoeGermuska** [comment]
verified
