### ISSUE TITLE
chmod issue with 02_download_acs_5yr.sh due to the change in directory structure by Census

### ISSUE THREAD

**Issue by thisisbinod** [censusreporter/census-postgres-scripts#3]
I couldn't remember if the issue was for 2011 or 2012 or both
Correct chmod should be
chmod 777 /mnt/tmp/acs2012_5yr/ /mnt/tmp/acs2012_5yr/tab4/ /mnt/tmp/acs2012_5yr/tab4/sumfile/ /mnt/tmp/acs2012_5yr/tab4/sumfile/prod/ /mnt/tmp/acs2012_5yr/tab4/sumfile/prod/2008thru2012/ /mnt/tmp/acs2012_5yr/tab4/sumfile/prod/2008thru2012/group1/ /mnt/tmp/acs2012_5yr/tab4/sumfile/prod/2008thru2012/group2/

chmod 644 /mnt/tmp/acs2012_5yr/tab4/sumfile/prod/2008thru2012/group1/* /mnt/tmp/acs2012_5yr/tab4/sumfile/prod/2008thru2012/group2/*

**Comment by iandees** [comment]
Closing as stale.
